# Generated by Django 4.2.1 on 2023-06-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='texto',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
