# Generated by Django 4.2.1 on 2023-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantae', '0003_rename_substitulo_blog_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='texto_base',
            field=models.CharField(max_length=150),
        ),
    ]
