# Generated by Django 4.2.1 on 2023-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantae', '0004_alter_planta_texto_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='nome',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
